/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import Classes.Computer;
import javax.swing.JOptionPane;

/**
 *
 * @author Katiuska Torres
 */
public class Entry_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Entry_Interface
     */
    public Entry_Interface() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_absolute = new javax.swing.JPanel();
        Panel_title = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Start_button = new javax.swing.JButton();
        Velocity = new javax.swing.JTextField();
        Panel_velocity = new javax.swing.JPanel();
        Velocity_text = new javax.swing.JLabel();
        Space = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_absolute.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_title.setBackground(new java.awt.Color(255, 255, 255));
        Panel_title.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102)));

        Title.setBackground(new java.awt.Color(0, 0, 0));
        Title.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Simulacion");

        javax.swing.GroupLayout Panel_titleLayout = new javax.swing.GroupLayout(Panel_title);
        Panel_title.setLayout(Panel_titleLayout);
        Panel_titleLayout.setHorizontalGroup(
            Panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_titleLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        Panel_titleLayout.setVerticalGroup(
            Panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_titleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        Panel_absolute.add(Panel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 470, -1));

        Start_button.setBackground(new java.awt.Color(255, 255, 255));
        Start_button.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        Start_button.setForeground(new java.awt.Color(0, 0, 0));
        Start_button.setText("Comenzar");
        Start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_buttonActionPerformed(evt);
            }
        });
        Panel_absolute.add(Start_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 170, 70));

        Velocity.setBackground(new java.awt.Color(255, 255, 255));
        Velocity.setForeground(new java.awt.Color(0, 0, 0));
        Velocity.setText("Velocity");
        Panel_absolute.add(Velocity, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 100, 30));

        Panel_velocity.setBackground(new java.awt.Color(255, 255, 255));

        Velocity_text.setBackground(new java.awt.Color(0, 0, 0));
        Velocity_text.setForeground(new java.awt.Color(0, 0, 0));
        Velocity_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Velocity_text.setText("Velocidad Inicial:");
        Velocity_text.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout Panel_velocityLayout = new javax.swing.GroupLayout(Panel_velocity);
        Panel_velocity.setLayout(Panel_velocityLayout);
        Panel_velocityLayout.setHorizontalGroup(
            Panel_velocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_velocityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Velocity_text, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_velocityLayout.setVerticalGroup(
            Panel_velocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Velocity_text, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Panel_absolute.add(Panel_velocity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, 30));

        Space.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cosmos.jpg"))); // NOI18N
        Space.setText("jLabel1");
        Panel_absolute.add(Space, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_absolute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_absolute, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isValidNumber(String text) {
    try {
        Integer.parseInt(text); // Intenta convertir el texto a un número entero
        return true; // Si la conversión es exitosa, devuelve true
    } catch (NumberFormatException e ) {
        return false; // Si ocurre una excepción, devuelve false
    }
    

}
    private void Start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_buttonActionPerformed
          String velocityText = Velocity.getText();
    if (isValidNumber(velocityText)) {
        int velocity = Integer.parseInt(velocityText);
        
        Star_wars_vs_Star_Trek starWarsVsStarTrek = new Star_wars_vs_Star_Trek();
        Computer com = new Computer(velocity);
        com.simulation();
        GUIManager observer = new GUIManager(starWarsVsStarTrek , com); 
        observer.start(); 
        starWarsVsStarTrek.setVisible(true); 
        
        this.dispose(); 
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para la velocidad.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Start_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entry_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entry_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entry_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entry_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entry_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_absolute;
    private javax.swing.JPanel Panel_title;
    private javax.swing.JPanel Panel_velocity;
    private javax.swing.JLabel Space;
    private javax.swing.JButton Start_button;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField Velocity;
    private javax.swing.JLabel Velocity_text;
    // End of variables declaration//GEN-END:variables
}
